# Generated by Django 5.0.1 on 2024-01-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cars", "0005_rename_car_value_carinventory_cars_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
    ]
